project:
  type: website
  output-dir: .

website:
  title: HR-VILAGE-3K3M
  navbar:
    left:
      - href: https://xuejunsun98.github.io/HR-VILAGE-3K3M/
        text: Home
    right:
      - href: Affymetrix_microarray_process.qmd
        text: Document

  sidebar:
    style: "floating"
    contents:
      - section: "Data Preprocessing"
        contents:
          - href: Affymetrix_microarray_process.qmd
            text: Affymetrix Microarray Process
          - href: Illumina_microarray_process.qmd
            text: Illumina Microarray Process
          - href: RNAseq_Process.qmd
            text: RNA-seq Process
          - href: Meta_preprocess_demo.qmd
            text: Single-Cell Metadata Preprocessing Demo
          - href: Single_cell_merge_data_demo.qmd
            text: Single-Cell Merged Data Exploration Demo
      - section: "Outcome Prediction Using Longitudinal Bulk Data"
        contents:
          - href: Antibody_Responder_Prediction.qmd
            text: Antibody Responder Prediction
      - section: "Cell Type Annotation Using Paired Bulk and Single-Cell Data"
        contents:
          - href: bulk_sc_paired.qmd
            text: Paired Bulk scRNA-seq Analysis
